-- This file does not exist.

























































































































































































([[This file was protected with MoonSec V3]]):gsub('.+', (function(a) _VjRYJcDHenDa = a; end)); return(function(r,...)local a;local l;local h;local f;local t;local d;local e=24915;local n=0;local o={};while n<850 do n=n+1;while n<0x1ee and e%0xa50<0x528 do n=n+1 e=(e-618)%10448 local c=n+e if(e%0x405c)>0x202e then e=(e*0xae)%0x3134 while n<0xb0 and e%0x108c<0x846 do n=n+1 e=(e+531)%3796 local l=n+e if(e%0x3ea8)>=0x1f54 then e=(e*0x3be)%0x82e3 local e=62067 if not o[e]then o[e]=0x1 end elseif e%2~=0 then e=(e-0xb0)%0x8fb9 local e=81870 if not o[e]then o[e]=0x1 h=tonumber;end else e=(e-0x1e9)%0x17be n=n+1 local e=85957 if not o[e]then o[e]=0x1 a="\4\8\116\111\110\117\109\98\101\114\107\111\103\108\85\76\107\117\0\6\115\116\114\105\110\103\4\99\104\97\114\72\65\107\97\72\71\107\107\0\6\115\116\114\105\110\103\3\115\117\98\72\97\68\87\116\119\121\109\0\6\115\116\114\105\110\103\4\98\121\116\101\79\81\109\101\111\117\115\99\0\5\116\97\98\108\101\6\99\111\110\99\97\116\72\80\122\70\90\84\109\85\0\5\116\97\98\108\101\6\105\110\115\101\114\116\84\74\119\113\73\90\89\68\5";end end end elseif e%2~=0 then e=(e+0x330)%0x90a6 while n<0x316 and e%0x395c<0x1cae do n=n+1 e=(e-364)%29804 local a=n+e if(e%0x2be8)<=0x15f4 then e=(e*0x2c0)%0x3bfd local e=19887 if not o[e]then o[e]=0x1 t={};end elseif e%2~=0 then e=(e-0x374)%0x3a5e local e=59928 if not o[e]then o[e]=0x1 d=function(d)local e=0x01 local function o(n)e=e+n return d:sub(e-n,e-0x01)end while true do local n=o(0x01)if(n=="\5")then break end local e=f.byte(o(0x01))local e=o(e)if n=="\2"then e=t.koglULku(e)elseif n=="\3"then e=e~="\0"elseif n=="\6"then l[e]=function(e,n)return r(8,nil,r,n,e)end elseif n=="\4"then e=l[e]elseif n=="\0"then e=l[e][o(f.byte(o(0x01)))];end local n=o(0x08)t[n]=e end end end else e=(e*0x1b8)%0x3cb n=n+1 local e=37788 if not o[e]then o[e]=0x1 end end end else e=(e+0x3f7)%0x753d n=n+1 while n<0x8c and e%0x4904<0x2482 do n=n+1 e=(e+365)%29539 local d=n+e if(e%0x43e0)>=0x21f0 then e=(e*0x4f)%0x17d6 local e=23684 if not o[e]then o[e]=0x1 l=getfenv and getfenv();end elseif e%2~=0 then e=(e+0x1f1)%0x9f3b local e=62417 if not o[e]then o[e]=0x1 l=(not l)and _ENV or l;end else e=(e-0x10d)%0x5996 n=n+1 local e=46383 if not o[e]then o[e]=0x1 f=string;end end end end end e=(e*371)%34478 end d(a);local e={};for n=0x0,0xff do local o=t.HAkaHGkk(n);e[n]=o;e[o]=n;end local function c(n)return e[n];end local f=(function(f,r)local a,o=0x01,0x10 local n={{},{},{}}local l=-0x01 local e=0x01 local d=f while true do n[0x03][t.HaDWtwym(r,e,(function()e=a+e return e-0x01 end)())]=(function()l=l+0x01 return l end)()if l==(0x0f)then l=""o=0x000 break end end local l=#r while e<l+0x01 do n[0x02][o]=t.HaDWtwym(r,e,(function()e=a+e return e-0x01 end)())o=o+0x01 if o%0x02==0x00 then o=0x00 t.TJwqIZYD(n[0x01],(c((((n[0x03][n[0x02][0x00]]or 0x00)*0x10)+(n[0x03][n[0x02][0x01]]or 0x00)+d)%0x100)));d=f+d;end end return t.HPzFZTmU(n[0x01])end);d(f(242,"yd-/^;6D}e>KBz2Md/"));d(f(235,"_D?gKTiF7Y8/*NIzDTgo/?*7N/IFRDWz*DgiT*iY7DYg7AYD/i*DHTIzz8N?I7i7FQ7g8g/78NIgNNzaDKg/?iT*(8?g8g/8*iItz/IzzK?*ggTzi8iK7iKKTzIDzFS8DigngIzDiIFFYz8g/N*Izw,FG/P,Kig/KzD??/8Y/?N8IgYTDDDIgKT*iY7FF77?Y?N8*zJTD7/8NFTgT8FI7*YY/N/zIFIYzzDI?*giKFi/iD7F/KYzND778:GK?7g/iDFD7YTzYi//IDI7I7?g?OKIINZ?787Y8i*i*7NuM?0/DDKKKNiYDD?TF?*K*FIzz/D/?Ig8?gz8DgYK8K/NNgIiz?#*D8K5T?gFKNFgFI778IFa780ID-?iKTTg!Y7NY//?/7*zI*I*DY?7?/ixi*i8Y7K?TYNNI/j?(7Dzg*gYK77lFKYN/F/NIIY?87?7gzK/iT7SFY88Yi8N/FNY}IEN*NIKiiiN7YYF88No*7N7N*JY?iK?KTFJDYg?/x/YIDI8Y*D??NKTT8F?7?7N7FYTNN*II8zN*?"));local e=(-2249+(function()local l,o=0,1;(function(n,o,e)o(n(e,n and n,n)and e(e,n,n),o(o,e,e)and o(e,e,n),e(n,n,e))end)(function(n,e,d)if l>422 then return n end l=l+1 o=(o+325)%15079 if(o%1766)>883 then return d(d(e,e and e,d and e),n(e,n,e),n(e,d,d))else return n end return n end,function(e,d,n)if l>248 then return e end l=l+1 o=(o+963)%9467 if(o%998)>499 then return e(e(d and e,n,d and e),n(d,e,n),n(d,e,n))else return e end return n end,function(n,d,e)if l>377 then return e end l=l+1 o=(o*544)%18668 if(o%1446)>723 then return e else return n(e(d,e,n),d(n,n,n),e(e,e,e))end return n(n(n,d,e),d(e,n,d)and n(d,d,d),e(n and n,e,e)and e(d,n,e))end)return o;end)())local y=(getfenv)or(function()return _ENV end);local u=t.SMpOchYu or t.VnhVvmVo;local l=2;local d=3;local p=1;local c=4;local function k(_,...)local s=f(e,"T)<Aq!=,-_BJx{FoF<B=,_qx<<oxx!_-=JBB- q!)Jo{{)B<=xqq)k,o!B<<o!x-u!{AB<-<qJ)oo_x!=qA-m{Bo-A!<<!o-A<oo{FB_)B;AJ{_N=A-A,-qJ){{!JB-J!B<))!F=Ju--!qAA{Jxo_{,Gqq<rx=xx_o,?{qJ),,qB){qo)_IZJJ_!!_q!o_{zxi_xq!A!BBB)q{<YoA)BR){!J<A<qJ<)o,xA!),JA-){_{xG_!=!A{%){<J=,Bqx{J}!xBB-=ooBoBFox<_qqxA)5<_<_JqJFxJF_)=qA,rBo{AxxA!_AXoxxoB<FxB{,{!=AQ(A{<A{)qF4JA-=x=_!={A)),{_JJ<)=Bxq_,=BB!-q!,<=ox_=!FA)A_))FFJ)_R==<Jx-{tBo-L)!)Boxx-=),xA{}{F=xu_A=<A{xxB),!qo<)oqx<_J=_A_z{F)J)-_!{AAf){,B_,=q-!=)=F!x-_)=<qqF-o{{y,{=,<A)JFA_-q{!_AJoJJF_x,-!_Fqx#xq=FqJs,>{F,J!_A=1)=x!xx-!q=q=o_{B_oB-!!<!o)FA,o_qABo!)!_F__={!J<<oBB<_{A_A-oq{q_J,xoJ{!_F,)qq-q!A<JFox=_F=BqB)<F,!-A)oJxFB)x_JB,o!o<Foq{A_F,oF0J<-!!-<JoFAJ_xJ,q{<qowxA_=J)Js-A!<oxF{xoA)q{{qB,,BJ!_q=,A=dxB==Fq)!,)_v<-x_-={qJ)<o<J<_-=_<F#F{<J)-A!x<Iox{!=<=Bq_)BBo_!_!=_)!)<x=B=-A!5<xx6x!_J=Fq=<qFxx!_,<Jq)s,{JJJqB!=<=o!xJB{Axq{)qFox,!J=oA,)_FBJ_-!o)xq_,=B!=)2FAJ=-_=q<o8<{!B_,JqF<)G={,_B={q9),F=J_-x,)Ao1!{-BJ-A!)<qo,o Bq,vqA)=FoJx_ =<AJk-{oBo-)!q<,?dx{B),AqB)BFxJo_<=xA-zx{FJ)-J!,<Bo{{)BA,=q_)xn)x<_!=-AxUFF)Jq__=!<{L){AB-,_qx)oo<xB_-=JAF)<FqJ--B=oq-VA{=B_--qo<<o!{BB,=Fq))qFFJB-{=.q!)q{_Bx,o!J<!o-xJJz,oqq),FBxB_u=AA=)JFxBo-<!!AAoJxFB)-=qB)BF{xQ_{==A_mxo)x_-!!-<J(={)Bq,,!xA!oLxA_==BAxEoF<x,__!J<oH){,B,,Bq{qSo-x=_B=xqY)<oAJ-_{,AA)X,{,J_,{!V<Ao=xJ_x,?q<)-F-JJ-F=)AF#,{BB{-^!A<-o_xxJ),<q!)-FxJF_<=qA,)<{{J;-A!,<_oxxoB<");local n=0;t.LmRP_qGh(function()t.aTqeVtho()n=n+1 end)local function e(e,o)if o then return n end;n=e+n;end local o,n,a=r(0,r,e,s,t.OQmeousc);local function f()local o,n=t.OQmeousc(s,e(1,3),e(5,6)+2);e(2);return(n*256)+o;end;local b=true;local b=0 local function z()local l=n();local e=n();local d=1;local l=(o(e,1,20)*(2^32))+l;local n=o(e,21,31);local e=((-1)^o(e,32));if(n==0)then if(l==b)then return e*0;else n=1;d=0;end;elseif(n==2047)then return(l==0)and(e*(1/0))or(e*(0/0));end;return t.yUJExXyw(e,n-1023)*(d+(l/(2^52)));end;local g=n;local function k(n)local o;if(not n)then n=g();if(n==0)then return'';end;end;o=t.HaDWtwym(s,e(1,3),e(5,6)+n-1);e(n)local e=""for n=(1+b),#o do e=e..t.HaDWtwym(o,n,n)end return e;end;local b=#t.xuEFWMBS(h('\49.\48'))~=1 local e=n;local function ee(...)return{...},t.WRAYahVl('#',...)end local function m()local e={};local u={};local h={};local s={h,u,nil,e};local e=n()local r={}for l=1,e do local o=a();local e;if(o==0)then e=(a()~=#{});elseif(o==1)then local n=z();if b and t.dqsbBsSR(t.xuEFWMBS(n),'.(\48+)$')then n=t.mcHAtPWU(n);end e=n;elseif(o==3)then e=k();end;r[l]=e;end;for e=1,n()do u[e-(#{1})]=m();end;for u=1,n()do local e=a();if(o(e,1,1)==0)then local t=o(e,2,3);local a=o(e,4,6);local e={f(),f(),nil,nil};if(t==0)then e[d]=f();e[c]=f();elseif(t==#{1})then e[d]=n();elseif(t==_[2])then e[d]=n()-(2^16)elseif(t==_[3])then e[d]=n()-(2^16)e[c]=f();end;if(o(a,1,1)==1)then e[l]=r[e[l]]end if(o(a,2,2)==1)then e[d]=r[e[d]]end if(o(a,3,3)==1)then e[c]=r[e[c]]end h[u]=e;end end;s[3]=a();return s;end;local function k(o,e,n)local l=e;local l=n;return h(t.dqsbBsSR(t.dqsbBsSR(({t.LmRP_qGh(o)})[2],e),n))end local function j(b,e,a)local function m(...)local f,m,s,y,_,o,h,k,g,z,j,n;local e=0;while-1<e do if e>2 then if 4<e then if e~=6 then n=r(7);else e=-2;end else if e==3 then k={};g={...};else z=t.WRAYahVl('#',...)-1;j={};end end else if 1>e then f=r(6,96,1,11,b);m=r(6,44,2,4,b);else if e>1 then o=-41;h=-1;else s=r(6,91,3,30,b);_=ee y=0;end end end e=e+1;end;for e=0,z do if(e>=s)then k[e-s]=g[e+1];else n[e]=g[e+1];end;end;local e=z-s+1 local e;local r;local function s(...)while true do end end while true do if o<-40 then o=o+42 end e=f[o];r=e[p];if 14>=r then if 6>=r then if r>2 then if 5<=r then if 6>r then local t,a,b,s,r;t=e[l];a=n[e[d]];n[t+1]=a;n[t]=a[e[c]];o=o+1;e=f[o];n(e[l],e[d]);o=o+1;e=f[o];t=e[l]b,s=_(n[t](u(n,t+1,e[d])))h=s+t-1 r=0;for e=t,h do r=r+1;n[e]=b[r];end;o=o+1;e=f[o];t=e[l]n[t]=n[t](u(n,t+1,h))o=o+1;e=f[o];n[e[l]]();o=o+1;e=f[o];do return end;else local o=e[l]local l,e=_(n[o](u(n,o+1,e[d])))h=e+o-1 local e=0;for o=o,h do e=e+1;n[o]=l[e];end;end else if r>-1 then repeat if r~=4 then local l=e[l];local o=n[e[d]];n[l+1]=o;n[l]=o[e[c]];break;end;n[e[l]]=a[e[d]];until true;else n[e[l]]=a[e[d]];end end else if 1>r then local e=e[l]n[e]=n[e](u(n,e+1,h))else if r~=2 then o=e[d];else do return end;end end end else if 10>=r then if r<=8 then if 4~=r then repeat if r~=8 then do return end;break;end;for t=0,3 do if t<2 then if t<1 then n[e[l]]=(e[d]~=0);o=o+1;e=f[o];else a[e[d]]=n[e[l]];o=o+1;e=f[o];end else if t==3 then if(n[e[l]]==e[c])then o=o+1;else o=e[d];end;else n[e[l]]=a[e[d]];o=o+1;e=f[o];end end end until true;else do return end;end else if r==10 then n(e[l],e[d]);else n[e[l]]=(e[d]~=0);end end else if r<13 then if 9~=r then for c=29,67 do if r<12 then local r,a;for c=0,1 do if-1~=c then for h=43,79 do if 0<c then r=e[l];a=n[r];for e=r+1,e[d]do t.TJwqIZYD(a,n[e])end;break;end;n(e[l],e[d]);o=o+1;e=f[o];break;end;else r=e[l];a=n[r];for e=r+1,e[d]do t.TJwqIZYD(a,n[e])end;end end break;end;for t=0,6 do if 2<t then if t<=4 then if 0<t then for r=48,84 do if 3~=t then n(e[l],e[d]);o=o+1;e=f[o];break;end;a[e[d]]=n[e[l]];o=o+1;e=f[o];break;end;else a[e[d]]=n[e[l]];o=o+1;e=f[o];end else if 1<=t then for r=47,85 do if t~=6 then a[e[d]]=n[e[l]];o=o+1;e=f[o];break;end;n[e[l]]=a[e[d]];break;end;else a[e[d]]=n[e[l]];o=o+1;e=f[o];end end else if 0<t then if-1<=t then repeat if 2>t then a[e[d]]=n[e[l]];o=o+1;e=f[o];break;end;n(e[l],e[d]);o=o+1;e=f[o];until true;else a[e[d]]=n[e[l]];o=o+1;e=f[o];end else n(e[l],e[d]);o=o+1;e=f[o];end end end break;end;else local r,a;for c=0,1 do if-1~=c then for h=43,79 do if 0<c then r=e[l];a=n[r];for e=r+1,e[d]do t.TJwqIZYD(a,n[e])end;break;end;n(e[l],e[d]);o=o+1;e=f[o];break;end;else r=e[l];a=n[r];for e=r+1,e[d]do t.TJwqIZYD(a,n[e])end;end end end else if 13<r then local o=e[l];local l=n[o];for e=o+1,e[d]do t.TJwqIZYD(l,n[e])end;else n[e[l]]={};end end end end else if r>=22 then if 26>r then if r>23 then if r>20 then for t=34,97 do if r>24 then if(n[e[l]]==e[c])then o=o+1;else o=e[d];end;break;end;a[e[d]]=n[e[l]];break;end;else if(n[e[l]]==e[c])then o=o+1;else o=e[d];end;end else if 23~=r then o=e[d];else a[e[d]]=n[e[l]];end end else if 28>r then if r>26 then if(n[e[l]]==e[c])then o=o+1;else o=e[d];end;else local e=e[l]n[e]=n[e](u(n,e+1,h))end else if r~=25 then for o=30,78 do if r<29 then local o=e[l];local l=n[o];for e=o+1,e[d]do t.TJwqIZYD(l,n[e])end;break;end;n[e[l]]();break;end;else local o=e[l];local l=n[o];for e=o+1,e[d]do t.TJwqIZYD(l,n[e])end;end end end else if 18>r then if 16>r then local o=e[l]local l,e=_(n[o](u(n,o+1,e[d])))h=e+o-1 local e=0;for o=o,h do e=e+1;n[o]=l[e];end;else if 14<=r then for o=17,76 do if 16<r then n[e[l]]=a[e[d]];break;end;n(e[l],e[d]);break;end;else n[e[l]]=a[e[d]];end end else if r>=20 then if r==21 then n[e[l]]=(e[d]~=0);else n[e[l]]();end else if r==18 then n[e[l]]={};else local l=e[l];local o=n[e[d]];n[l+1]=o;n[l]=o[e[c]];end end end end end o=1+o;end;end;return m end;local d=0xff;local c={};local r=(1);local l='';(function(n)local o=n local f=0x00 local e=0x00 o={(function(t)if f>0x21 then return t end f=f+1 e=(e+0x5c0-t)%0x3d return(e%0x03==0x0 and(function(o)if not n[o]then e=e+0x01 n[o]=(0xbf);d[2]=(d[2]*(k(function()c()end,u(l))-k(d[1],u(l))))+1;c[r]={};d=d[2];r=r+d;end return true end)'gjbCe'and o[0x2](0x198+t))or(e%0x03==0x2 and(function(o)if not n[o]then e=e+0x01 n[o]=(0x40);end return true end)'PRbRe'and o[0x3](t+0x3bb))or(e%0x03==0x1 and(function(o)if not n[o]then e=e+0x01 n[o]=(0x11);end return true end)'MdgEc'and o[0x1](t+0x3ce))or t end),(function(t)if f>0x27 then return t end f=f+1 e=(e+0x90d-t)%0x4b return(e%0x03==0x1 and(function(o)if not n[o]then e=e+0x01 n[o]=(0xe1);l='\37';d={function()d()end};l=l..'\100\43';end return true end)'sDLmU'and o[0x3](0x3d1+t))or(e%0x03==0x0 and(function(o)if not n[o]then e=e+0x01 n[o]=(0x16);end return true end)'C_hwE'and o[0x1](t+0x306))or(e%0x03==0x2 and(function(o)if not n[o]then e=e+0x01 n[o]=(0x23);end return true end)'CEJoB'and o[0x2](t+0x1fd))or t end),(function(a)if f>0x2b then return a end f=f+1 e=(e+0x1150-a)%0x32 return(e%0x03==0x1 and(function(o)if not n[o]then e=e+0x01 n[o]=(0xdb);c[r]=y();r=r+d;end return true end)'XgEtr'and o[0x3](0x66+a))or(e%0x03==0x2 and(function(o)if not n[o]then e=e+0x01 n[o]=(0x5e);l={l..'\58 a',l};c[r]=m();r=r+((not t.mEAQGvKA)and 1 or 0);l[1]='\58'..l[1];d[2]=0xff;end return true end)'jOteR'and o[0x1](a+0xe0))or(e%0x03==0x0 and(function(o)if not n[o]then e=e+0x01 n[o]=(0xef);end return true end)'QmvZS'and o[0x2](a+0xcc))or a end)}o[0x2](0x45c)end){};local e=j(u(c));return e(...);end return k((function()local n={}local e=0x01;local o;if t.mEAQGvKA then o=t.mEAQGvKA(k)else o=''end if t.dqsbBsSR(o,t.SCfXoeJW)then e=e+0;else e=e+1;end n[e]=0x02;n[n[e]+0x01]=0x03;return n;end)(),...)end)((function(n,e,o,l,d,t)local t;if 3<n then if n>5 then if n<7 then do return d[o]end;else if 3<n then for e=43,91 do if 8~=n then do return setmetatable({},{['__\99\97\108\108']=function(e,l,o,d,n)if n then return e[n]elseif d then return e else e[l]=o end end})end break;end;do return o(n,nil,o);end break;end;else do return setmetatable({},{['__\99\97\108\108']=function(e,l,d,o,n)if n then return e[n]elseif o then return e else e[l]=d end end})end end end else if 1<=n then repeat if 4<n then local n=l;do return function()local e=e(o,n(n,n),n(n,n));n(1);return e;end;end;break;end;local n=l;local t,d,l=d(2);do return function()local e,r,o,f=e(o,n(n,n),n(n,n)+3);n(4);return(f*t)+(o*d)+(r*l)+e;end;end;until true;else local n=l;do return function()local e=e(o,n(n,n),n(n,n));n(1);return e;end;end;end end else if n<=1 then if n>0 then do return function(n,e,o)if o then local e=(n/2^(e-1))%2^((o-1)-(e-1)+1);return e-e%1;else local e=2^(e-1);return(n%(e+e)>=e)and 1 or 0;end;end;end;else do return e(1),e(4,d,l,o,e),e(5,d,l,o)end;end else if n~=3 then do return 16777216,65536,256 end;else do return e(1),e(4,d,l,o,e),e(5,d,l,o)end;end end end end),...)



























































































                    
